#include "nrc/nrc_pass.h"

// Embedded SPIR-V of the compiled NRC compute shaders. Generated by the
// host's compile_slang CMake rule.
#include "_autogen/nrc_cache_query.comp.slang.h"
#include "_autogen/nrc_record_complete.comp.slang.h"
#include "_autogen/nrc_train.comp.slang.h"
#include "_autogen/nrc_optimizer.comp.slang.h"
#include "_autogen/nrc_compose.comp.slang.h"

#include <cassert>
#include <cmath>
#include <cstring>
#include <random>
#include <stdexcept>
#include <vector>

namespace nrc {

// Sizes must agree with the Slang structs in shaders/nrc_common.h.slang.
// See tests/test_feature_pack_sizes.cpp for the matching static_assert.
static constexpr VkDeviceSize kTrainingRecordBytes = 140;
static constexpr VkDeviceSize kQueryRecordBytes    = 80;

// IEEE-754 fp32 -> fp16 conversion. We keep it simple (no proper rounding,
// no denormals) — adequate for weight initialization where values are already
// small and well-behaved.
static uint16_t floatToHalf(float f) {
    uint32_t u; std::memcpy(&u, &f, 4);
    uint32_t sign     = (u >> 16) & 0x8000u;
    int32_t  exponent = ((u >> 23) & 0xff) - 127 + 15;
    uint32_t mantissa = u & 0x7fffffu;

    if (exponent <= 0) return static_cast<uint16_t>(sign);                   // underflow -> signed zero
    if (exponent >= 31) return static_cast<uint16_t>(sign | 0x7c00u);        // overflow -> infinity

    return static_cast<uint16_t>(sign | (exponent << 10) | (mantissa >> 13));
}

NrcPass::NrcPass() = default;

NrcPass::~NrcPass() {
    // Callers must call destroy() before the device is torn down.
    assert(!m_initialized && "NrcPass::destroy() not called before destruction");
}

// Helper: find a memory type matching typeFilter and having all required flags.
static uint32_t findMemoryType(VkPhysicalDevice physDev,
                                uint32_t         typeFilter,
                                VkMemoryPropertyFlags required) {
    VkPhysicalDeviceMemoryProperties mp;
    vkGetPhysicalDeviceMemoryProperties(physDev, &mp);
    for (uint32_t i = 0; i < mp.memoryTypeCount; ++i) {
        const bool typeAllowed = (typeFilter & (1u << i)) != 0;
        const bool flagsOk     = (mp.memoryTypes[i].propertyFlags & required) == required;
        if (typeAllowed && flagsOk) return i;
    }
    return UINT32_MAX;
}

NrcPass::Buffer NrcPass::allocate(VkDeviceSize size, VkBufferUsageFlags usage) {
    Buffer b;
    b.size = size;

    VkBufferCreateInfo bi{};
    bi.sType       = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
    bi.size        = size;
    bi.usage       = usage;
    bi.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
    if (vkCreateBuffer(m_device, &bi, nullptr, &b.handle) != VK_SUCCESS) {
        throw std::runtime_error("nrc: vkCreateBuffer failed");
    }

    VkMemoryRequirements mr;
    vkGetBufferMemoryRequirements(m_device, b.handle, &mr);

    uint32_t memType = findMemoryType(m_physicalDevice, mr.memoryTypeBits,
                                      VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
    if (memType == UINT32_MAX) {
        throw std::runtime_error("nrc: no device-local memory type available");
    }

    // Every allocation may be used for buffer-device-address (shader_device_address).
    // Tack on the ALLOCATE_DEVICE_ADDRESS flag unconditionally — harmless if the
    // buffer never queries its address.
    VkMemoryAllocateFlagsInfo flagsInfo{};
    flagsInfo.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_FLAGS_INFO;
    flagsInfo.flags = VK_MEMORY_ALLOCATE_DEVICE_ADDRESS_BIT;

    VkMemoryAllocateInfo ai{};
    ai.sType           = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
    ai.pNext           = &flagsInfo;
    ai.allocationSize  = mr.size;
    ai.memoryTypeIndex = memType;
    if (vkAllocateMemory(m_device, &ai, nullptr, &b.memory) != VK_SUCCESS) {
        vkDestroyBuffer(m_device, b.handle, nullptr);
        throw std::runtime_error("nrc: vkAllocateMemory failed");
    }
    vkBindBufferMemory(m_device, b.handle, b.memory, 0);
    return b;
}

void NrcPass::freeBuffer(Buffer& b) {
    if (b.handle) vkDestroyBuffer(m_device, b.handle, nullptr);
    if (b.memory) vkFreeMemory(m_device, b.memory, nullptr);
    b = {};
}

void NrcPass::fillWeightStaging(uint32_t seed) {
    if (!m_weightStagingMapped) return;

    MlpLayout rowMajorLayout = computeMlpLayout(m_device,
        VK_COOPERATIVE_VECTOR_MATRIX_LAYOUT_ROW_MAJOR_NV);
    assert(rowMajorLayout.totalBytes <= m_weightStaging.size);

    std::mt19937 rng(seed);
    uint8_t* dst = static_cast<uint8_t*>(m_weightStagingMapped);
    std::memset(dst, 0, rowMajorLayout.totalBytes);

    for (int i = 0; i < kNrcNumLayers; ++i) {
        // He/Xavier for ReLU: std = sqrt(2 / fan_in).
        float fanIn = static_cast<float>(rowMajorLayout.cols[i]);
        std::normal_distribution<float> dist(0.0f, std::sqrt(2.0f / fanIn));

        const uint32_t nElem = rowMajorLayout.rows[i] * rowMajorLayout.cols[i];
        uint16_t* w = reinterpret_cast<uint16_t*>(dst + rowMajorLayout.weightOffset[i]);
        for (uint32_t j = 0; j < nElem; ++j)
            w[j] = floatToHalf(dist(rng));

        // Biases remain zero; the NRC output layer is linear and inference
        // clamps negative radiance estimates.
    }
}

void NrcPass::resetTrainingState() {
    // Calibrate the initial training-ray threshold from the current render
    // extent when available. This matters while training is locked, because
    // the adaptive controller is not allowed to correct the probability.
    //   threshold = (pathsTarget / (W * H)) * 2^32
    uint32_t width  = (m_renderWidth  > 0) ? m_renderWidth  : m_params.frameWidth;
    uint32_t height = (m_renderHeight > 0) ? m_renderHeight : m_params.frameHeight;
    double pixels = double(width) * double(height);
    double fraction = double(m_params.trainingPathsTarget) / pixels;
    double t = fraction * 4294967296.0;   // 2^32
    if (t < 1.0)        t = 1.0;
    if (t > 4.29e9)     t = 4.29e9;
    m_trainingRayThreshold = uint32_t(t);

    m_lastKnownRecordCount = 0u;
    m_frameIdx             = 0u;
    m_trainStepIdx         = 0u;
    m_adamStep             = 0u;

    if (m_countReadbackMapped)
        std::memset(m_countReadbackMapped, 0, 64);
}

void NrcPass::init(VkDevice device, VkPhysicalDevice physDev, const NrcParams& params) {
    assert(!m_initialized);
    m_device         = device;
    m_physicalDevice = physDev;
    m_params         = params;

    const VkBufferUsageFlags ssbo = VK_BUFFER_USAGE_STORAGE_BUFFER_BIT
                                  | VK_BUFFER_USAGE_TRANSFER_DST_BIT
                                  | VK_BUFFER_USAGE_TRANSFER_SRC_BIT
                                  // vkCmdConvertCooperativeVectorMatrixNV uses
                                  // device addresses in its src/dst fields.
                                  | VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT;

    // Compute MLP layout: ask the driver how big each weight matrix is in
    // TrainingOptimal layout. This drives the device-side weight-buffer size.
    m_mlpLayout = computeMlpLayout(m_device, VK_COOPERATIVE_VECTOR_MATRIX_LAYOUT_TRAINING_OPTIMAL_NV);

    m_trainingRecords = allocate(params.trainingRecordsPerFrame * kTrainingRecordBytes, ssbo);
    m_queryRecords    = allocate(static_cast<VkDeviceSize>(params.frameWidth)
                                 * params.frameHeight * kQueryRecordBytes, ssbo);
    m_trainingCount   = allocate(256, ssbo);
    m_queryCount      = allocate(256, ssbo);
    m_primaryWeights  = allocate(m_mlpLayout.totalBytes,     ssbo);
    m_optimalWeights  = allocate(m_mlpLayout.totalBytes,     ssbo);
    m_emaWeights      = allocate(m_mlpLayout.totalBytes,     ssbo);
    // Adam stores two fp32 moments per fp16 parameter: elementCount is
    // totalBytes / 2, so moments need elementCount * 2 * sizeof(float).
    m_adamMoments     = allocate(4 * m_mlpLayout.totalBytes, ssbo);
    m_gradients       = allocate(m_mlpLayout.totalBytes,     ssbo);

    // NRC cache-contribution buffer: float4 per pixel (16 B).
    // Sized at the init-time upper bound (typically 1920x1080); setRenderSize()
    // at frame time picks a smaller stride. TODO(Task 6): make buffer size
    // dynamic if needed — e.g. if the host window can grow beyond the init
    // upper bound, we'd need to re-allocate.
    m_contribBuffer = allocate(
        static_cast<VkDeviceSize>(params.frameWidth) * params.frameHeight * 16,
        ssbo);

    // §1 path-prefix buffer: float4 per pixel (ray-gen writes each frame).
    // TODO(Task 6): make buffer size dynamic if needed.
    m_pathPrefixBuffer = allocate(
        static_cast<VkDeviceSize>(params.frameWidth) * params.frameHeight * 16,
        ssbo);

    // Training-targets buffer: float4 per training record.
    m_trainingTargets = allocate(params.trainingRecordsPerFrame * 16, ssbo);

    // Host-visible staging buffer for Xavier weights. Sized to the row-major
    // weight layout (may differ from device's TrainingOptimal totalBytes —
    // compute a row-major layout to find the correct staging size).
    MlpLayout rowMajorLayout = computeMlpLayout(m_device,
        VK_COOPERATIVE_VECTOR_MATRIX_LAYOUT_ROW_MAJOR_NV);
    {
        VkBufferCreateInfo bi{};
        bi.sType       = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
        bi.size        = rowMajorLayout.totalBytes;
        bi.usage       = VK_BUFFER_USAGE_TRANSFER_SRC_BIT
                       | VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT;
        bi.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
        if (vkCreateBuffer(m_device, &bi, nullptr, &m_weightStaging.handle) != VK_SUCCESS)
            throw std::runtime_error("nrc: weightStaging vkCreateBuffer failed");
        m_weightStaging.size = rowMajorLayout.totalBytes;

        VkMemoryRequirements mr;
        vkGetBufferMemoryRequirements(m_device, m_weightStaging.handle, &mr);
        uint32_t memType = findMemoryType(m_physicalDevice, mr.memoryTypeBits,
            VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);
        if (memType == UINT32_MAX) throw std::runtime_error("nrc: no host-visible memory");

        VkMemoryAllocateFlagsInfo flagsInfo{};
        flagsInfo.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_FLAGS_INFO;
        flagsInfo.flags = VK_MEMORY_ALLOCATE_DEVICE_ADDRESS_BIT;

        VkMemoryAllocateInfo ai{};
        ai.sType           = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
        ai.pNext           = &flagsInfo;
        ai.allocationSize  = mr.size;
        ai.memoryTypeIndex = memType;
        if (vkAllocateMemory(m_device, &ai, nullptr, &m_weightStaging.memory) != VK_SUCCESS)
            throw std::runtime_error("nrc: weightStaging vkAllocateMemory failed");
        vkBindBufferMemory(m_device, m_weightStaging.handle, m_weightStaging.memory, 0);
        vkMapMemory(m_device, m_weightStaging.memory, 0, VK_WHOLE_SIZE, 0,
                    &m_weightStagingMapped);
    }

    fillWeightStaging(0xC0FFEEu);

    // Debug readback buffer: 2 uints (training count, query count). Host-visible,
    // host-coherent so we don't need flushes. Used for smoke tests.
    {
        VkBufferCreateInfo bi{};
        bi.sType       = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
        bi.size        = 64;
        bi.usage       = VK_BUFFER_USAGE_TRANSFER_DST_BIT;
        bi.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
        if (vkCreateBuffer(m_device, &bi, nullptr, &m_countReadback.handle) != VK_SUCCESS)
            throw std::runtime_error("nrc: readback vkCreateBuffer failed");
        m_countReadback.size = 64;

        VkMemoryRequirements mr;
        vkGetBufferMemoryRequirements(m_device, m_countReadback.handle, &mr);
        uint32_t memType = findMemoryType(m_physicalDevice, mr.memoryTypeBits,
            VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);
        if (memType == UINT32_MAX) throw std::runtime_error("nrc: no host-visible memory type");

        VkMemoryAllocateInfo ai{};
        ai.sType           = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
        ai.allocationSize  = mr.size;
        ai.memoryTypeIndex = memType;
        if (vkAllocateMemory(m_device, &ai, nullptr, &m_countReadback.memory) != VK_SUCCESS)
            throw std::runtime_error("nrc: readback vkAllocateMemory failed");
        vkBindBufferMemory(m_device, m_countReadback.handle, m_countReadback.memory, 0);
        vkMapMemory(m_device, m_countReadback.memory, 0, VK_WHOLE_SIZE, 0, &m_countReadbackMapped);
    }

    createDescriptorSet();
    createCacheQueryPipeline();
    createRecordCompletePipeline();
    createTrainPipeline();
    createOptimizerPipeline();
    createComposePipeline();

    resetTrainingState();

    m_initialized = true;
}

void NrcPass::destroy() {
    if (!m_initialized) return;
    destroyComposePipeline();
    destroyOptimizerPipeline();
    destroyTrainPipeline();
    destroyRecordCompletePipeline();
    destroyCacheQueryPipeline();
    destroyDescriptorSet();
    if (m_countReadbackMapped) {
        vkUnmapMemory(m_device, m_countReadback.memory);
        m_countReadbackMapped = nullptr;
    }
    if (m_weightStagingMapped) {
        vkUnmapMemory(m_device, m_weightStaging.memory);
        m_weightStagingMapped = nullptr;
    }
    freeBuffer(m_weightStaging);
    freeBuffer(m_countReadback);
    freeBuffer(m_pathPrefixBuffer);
    freeBuffer(m_contribBuffer);
    freeBuffer(m_trainingTargets);
    freeBuffer(m_gradients);
    freeBuffer(m_adamMoments);
    freeBuffer(m_emaWeights);
    freeBuffer(m_optimalWeights);
    freeBuffer(m_primaryWeights);
    freeBuffer(m_queryCount);
    freeBuffer(m_trainingCount);
    freeBuffer(m_queryRecords);
    freeBuffer(m_trainingRecords);
    m_device         = VK_NULL_HANDLE;
    m_physicalDevice = VK_NULL_HANDLE;
    m_initialized    = false;
}

void NrcPass::recordFrame(VkCommandBuffer cmd, uint32_t /*frameIdx*/) {
    if (!m_initialized) return;

    if (m_retrainRequested) {
        const uint32_t seed = 0xC0FFEEu + (++m_retrainGeneration * 0x9E3779B9u);
        fillWeightStaging(seed);
        resetTrainingState();
        m_weightsInitialized = false;
        m_retrainRequested = false;
    }

    // Lazy weight initialization: on the first frame we have a command buffer,
    // issue the staging copy + row-major -> TrainingOptimal conversion.
    if (!m_weightsInitialized)
        initializeWeightsFirstFrame(cmd);

    // §3 (Task 3): read back the previous frame's counters from the host-
    // visible staging buffer (populated by last frame's recordFramePost copy
    // and made visible by the queue wait in the host frame loop). One frame
    // of staleness is acceptable — the LCG shuffle modulo tolerates it and
    // the P-controller is slow-moving.
    //
    // On frame 0 the staging buffer reads zero (init zeros it on map), so
    // m_lastKnownRecordCount stays 0 and dispatchTrain falls back to
    // trainingRecordsPerFrame for the shuffle modulo.
    if (m_countReadbackMapped) {
        const uint32_t* p = reinterpret_cast<const uint32_t*>(m_countReadbackMapped);
        m_lastKnownRecordCount = p[0];
    }

    // §3 (Task 3): host-side P-controller for the training-ray selection
    // threshold. Adjust the mask after the 128-frame warmup (spec §6 B28) so
    // that emitted records converge to trainingRecordsPerFrame. Multiplicative
    // gain (±5%) so each step is smooth; asymmetric hysteresis bands prevent
    // mask thrash when emission is already near target.
    if (!m_trainingLocked && m_frameIdx > 128u) {
        const uint32_t target    = m_params.trainingRecordsPerFrame;  // 65536
        const uint32_t hiTrigger = (target * 96u) / 100u;             // emit fewer above ~63k
        const uint32_t loTrigger = (target * 76u) / 100u;             // emit more below ~50k

        if (m_lastKnownRecordCount > hiTrigger) {
            uint64_t t = (uint64_t(m_trainingRayThreshold) * 95u) / 100u;
            m_trainingRayThreshold = uint32_t(t);
        } else if (m_lastKnownRecordCount < loTrigger && m_lastKnownRecordCount > 0u) {
            // Scale up — but don't overflow 32-bit. Cap at 0xFFFFFF00.
            uint64_t t = (uint64_t(m_trainingRayThreshold) * 105u) / 100u;
            if (t > 0xFFFFFF00ull) t = 0xFFFFFF00ull;
            m_trainingRayThreshold = uint32_t(t);
        }
    }
    // Increment the host-owned frame counter. Paper's warmup uses this — not
    // the renderer's frameCount, which can be Halton-index-overridden by DLSS.
    ++m_frameIdx;

    // Debug: always request readback for now. Harmless overhead (two 4-byte
    // copies to a mapped buffer per frame). Can be gated later.
    m_readbackRequested = true;

    // Per-frame, before the path tracer runs, reset the two atomic counters
    // that the ray-gen shader InterlockedAdds into. Training and query
    // buffers themselves don't need zeroing — unused entries are gated by
    // the counter values.
    //
    // vkCmdFillBuffer requires command-buffer recording state. The host
    // calls recordFrame() from its frame-recording function; we assume cmd
    // is in that state. Barriers between fill and shader-read come from
    // the caller (ray-gen's descriptor-set binding implies a barrier via
    // the host's existing synchronization).
    vkCmdFillBuffer(cmd, m_trainingCount.handle, 0, VK_WHOLE_SIZE, 0u);
    vkCmdFillBuffer(cmd, m_queryCount.handle,    0, VK_WHOLE_SIZE, 0u);

    // Pipeline barrier so subsequent shader reads see the zeros.
    VkBufferMemoryBarrier barriers[2] = {};
    for (int i = 0; i < 2; ++i) {
        barriers[i].sType = VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER;
        barriers[i].srcAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
        barriers[i].dstAccessMask = VK_ACCESS_SHADER_READ_BIT | VK_ACCESS_SHADER_WRITE_BIT;
        barriers[i].srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
        barriers[i].dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
        barriers[i].offset = 0;
        barriers[i].size   = VK_WHOLE_SIZE;
    }
    barriers[0].buffer = m_trainingCount.handle;
    barriers[1].buffer = m_queryCount.handle;

    vkCmdPipelineBarrier(cmd,
        VK_PIPELINE_STAGE_TRANSFER_BIT,
        VK_PIPELINE_STAGE_RAY_TRACING_SHADER_BIT_KHR
        | VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
        0,
        0, nullptr,
        2, barriers,
        0, nullptr);

    // g_nrcContrib is cleared per pixel by ray-gen when it writes g_pathPrefix.
    // That keeps no-query pixels from reusing stale cache values while avoiding
    // a full-buffer clear when the render size is smaller than the allocation.
}

void NrcPass::initializeWeightsFirstFrame(VkCommandBuffer cmd) {
    // Compute the row-major layout we uploaded into the staging buffer.
    MlpLayout rowMajor = computeMlpLayout(m_device,
        VK_COOPERATIVE_VECTOR_MATRIX_LAYOUT_ROW_MAJOR_NV);

    // 1) Weight matrices: convert row-major -> TrainingOptimal.
    // vkCmdConvertCooperativeVectorMatrixNV takes an array of infos; we do one
    // per layer (simpler, still cheap).
    for (int i = 0; i < kNrcNumLayers; ++i) {
        VkConvertCooperativeVectorMatrixInfoNV info{};
        info.sType = VK_STRUCTURE_TYPE_CONVERT_COOPERATIVE_VECTOR_MATRIX_INFO_NV;
        info.srcSize = rowMajor.weightSize[i];
        info.srcData.deviceAddress = [this]() {
            VkBufferDeviceAddressInfo bdai{};
            bdai.sType = VK_STRUCTURE_TYPE_BUFFER_DEVICE_ADDRESS_INFO;
            bdai.buffer = m_weightStaging.handle;
            return vkGetBufferDeviceAddress(m_device, &bdai);
        }() + rowMajor.weightOffset[i];
        size_t dstSizeInOut = m_mlpLayout.weightSize[i];
        info.pDstSize = &dstSizeInOut;
        info.dstData.deviceAddress = [this]() {
            VkBufferDeviceAddressInfo bdai{};
            bdai.sType = VK_STRUCTURE_TYPE_BUFFER_DEVICE_ADDRESS_INFO;
            bdai.buffer = m_primaryWeights.handle;
            return vkGetBufferDeviceAddress(m_device, &bdai);
        }() + m_mlpLayout.weightOffset[i];
        info.srcComponentType = VK_COMPONENT_TYPE_FLOAT16_KHR;
        info.dstComponentType = VK_COMPONENT_TYPE_FLOAT16_KHR;
        info.numRows    = rowMajor.rows[i];
        info.numColumns = rowMajor.cols[i];
        info.srcLayout  = VK_COOPERATIVE_VECTOR_MATRIX_LAYOUT_ROW_MAJOR_NV;
        info.srcStride  = rowMajor.cols[i] * kNrcElementBytes;
        info.dstLayout  = VK_COOPERATIVE_VECTOR_MATRIX_LAYOUT_TRAINING_OPTIMAL_NV;
        info.dstStride  = 0;
        vkCmdConvertCooperativeVectorMatrixNV(cmd, 1, &info);
    }

    // 2) Biases: simple buffer-to-buffer copy, layer by layer. Staging uses
    // row-major layout (biasOffset[i] in rowMajor); device uses m_mlpLayout
    // offsets. Sizes are the same (outputs * 2 bytes), no conversion needed.
    for (int i = 0; i < kNrcNumLayers; ++i) {
        VkBufferCopy bc{};
        bc.srcOffset = rowMajor.biasOffset[i];
        bc.dstOffset = m_mlpLayout.biasOffset[i];
        bc.size      = m_mlpLayout.biasSize[i];
        vkCmdCopyBuffer(cmd, m_weightStaging.handle, m_primaryWeights.handle, 1, &bc);
    }

    // 3) Barrier: primary is now valid. Copy to EMA.
    VkBufferMemoryBarrier bm{};
    bm.sType = VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER;
    bm.srcAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
    bm.dstAccessMask = VK_ACCESS_TRANSFER_READ_BIT;
    bm.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
    bm.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
    bm.buffer = m_primaryWeights.handle;
    bm.size   = VK_WHOLE_SIZE;
    vkCmdPipelineBarrier(cmd,
        VK_PIPELINE_STAGE_TRANSFER_BIT,
        VK_PIPELINE_STAGE_TRANSFER_BIT,
        0, 0, nullptr, 1, &bm, 0, nullptr);

    VkBufferCopy full{};
    full.srcOffset = 0; full.dstOffset = 0; full.size = m_mlpLayout.totalBytes;
    vkCmdCopyBuffer(cmd, m_primaryWeights.handle, m_emaWeights.handle, 1, &full);

    // 4) Zero m_gradients, m_adamMoments, and m_contribBuffer. The first two
    // are trainer-local and must start zero for Adam's running averages. The
    // contribBuffer starts at zero so frame 0's ray-gen reads zero
    // contributions (no cache history yet); cache-query at end of frame 0
    // writes the first real values.
    vkCmdFillBuffer(cmd, m_gradients.handle,    0, VK_WHOLE_SIZE, 0u);
    vkCmdFillBuffer(cmd, m_adamMoments.handle,  0, VK_WHOLE_SIZE, 0u);
    vkCmdFillBuffer(cmd, m_contribBuffer.handle, 0, VK_WHOLE_SIZE, 0u);
    vkCmdFillBuffer(cmd, m_pathPrefixBuffer.handle, 0, VK_WHOLE_SIZE, 0u);

    // Final barrier: everything needs to be shader-visible by the time
    // ray-gen (or the cache-query compute pass) runs.
    VkBufferMemoryBarrier bms[6] = {};
    for (int i = 0; i < 6; ++i) {
        bms[i].sType = VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER;
        bms[i].srcAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
        bms[i].dstAccessMask = VK_ACCESS_SHADER_READ_BIT | VK_ACCESS_SHADER_WRITE_BIT;
        bms[i].srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
        bms[i].dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
        bms[i].size = VK_WHOLE_SIZE;
    }
    bms[0].buffer = m_primaryWeights.handle;
    bms[1].buffer = m_emaWeights.handle;
    bms[2].buffer = m_gradients.handle;
    bms[3].buffer = m_adamMoments.handle;
    bms[4].buffer = m_contribBuffer.handle;
    bms[5].buffer = m_pathPrefixBuffer.handle;
    vkCmdPipelineBarrier(cmd,
        VK_PIPELINE_STAGE_TRANSFER_BIT,
        VK_PIPELINE_STAGE_RAY_TRACING_SHADER_BIT_KHR | VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
        0, 0, nullptr, 6, bms, 0, nullptr);

    m_weightsInitialized = true;
}

void NrcPass::recordFramePost(VkCommandBuffer cmd, uint32_t /*frameIdx*/) {
    if (!m_initialized) return;

    //  0. ray-gen has just run (caller's responsibility). It wrote training
    //     records, query records, counters, and g_pathPrefix.
    //  1. Barrier: ray-gen writes -> compute reads.
    //  2. Build training targets using this frame's records.
    //  3. 4 × (train → optimizer) Adam steps, same as today but now
    //     sequenced BEFORE cache-query so EMA weights seen by cache-query
    //     are this frame's just-updated values.
    //  4. Barrier: optimizer -> cache-query on EMA weights.
    //  5. Cache-query on THIS frame's queries -> writes g_nrcContrib.
    //  6. Barrier: cache-query + ray-gen -> compose.
    //  7. Compose: g_outImage = blend(history, prefix + contrib).

    if (m_enabled) {
        issueBarrierRayGenToCompute(cmd);
    }

    const bool trainThisFrame = m_enabled && m_trainPipeline
                             && (!m_trainingLocked || m_trainOneFrameRequested);

    if (trainThisFrame) {
        dispatchRecordCompletion(cmd);

        // §3 (Task 3): four Adam steps per frame, each on a disjoint
        // LCG-shuffled 16384-record slice of the 65536-record pool. Before
        // each dispatch, set m_trainStepIdx (dispatchTrain reads it into pc).
        for (uint32_t step = 0; step < m_params.adamStepsPerFrame; ++step) {
            m_trainStepIdx = step;

            // Clear gradients before each backward pass.
            vkCmdFillBuffer(cmd, m_gradients.handle, 0, VK_WHOLE_SIZE, 0u);
            VkBufferMemoryBarrier clearB{};
            clearB.sType = VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER;
            clearB.srcAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
            clearB.dstAccessMask = VK_ACCESS_SHADER_READ_BIT | VK_ACCESS_SHADER_WRITE_BIT;
            clearB.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
            clearB.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
            clearB.buffer = m_gradients.handle;
            clearB.size = VK_WHOLE_SIZE;
            vkCmdPipelineBarrier(cmd,
                VK_PIPELINE_STAGE_TRANSFER_BIT, VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
                0, 0, nullptr, 1, &clearB, 0, nullptr);

            dispatchTrain(cmd);
            dispatchOptimizer(cmd);
        }
    }

    if (m_enabled) {
        // Cache-query reads EMA weights; if training ran, this barrier makes
        // the just-updated weights visible.
        issueBarrierOptimizerToCacheQuery(cmd);

        // Cache-query on this frame's queries. Writes g_nrcContrib.
        dispatchCacheQuery(cmd);

        // Cache-query + ray-gen writes need to be visible to the compose pass.
        issueBarrierToCompose(cmd);

        // Compose: outImage = blend(history, prefix + contrib).
        dispatchCompose(cmd);
    }

    if (trainThisFrame && m_trainOneFrameRequested)
        m_trainOneFrameRequested = false;

    // If a debug readback was requested, copy the two atomic counters to the
    // host-visible staging buffer. A queue wait after command buffer submission
    // is required before readbackCounts() returns fresh values — the host is
    // responsible for that.
    if (m_readbackRequested) {
        VkBufferMemoryBarrier barrier{};
        barrier.sType         = VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER;
        barrier.srcAccessMask = VK_ACCESS_SHADER_WRITE_BIT;
        barrier.dstAccessMask = VK_ACCESS_TRANSFER_READ_BIT;
        barrier.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
        barrier.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
        barrier.size          = VK_WHOLE_SIZE;

        // Training count
        barrier.buffer = m_trainingCount.handle;
        vkCmdPipelineBarrier(cmd,
            VK_PIPELINE_STAGE_RAY_TRACING_SHADER_BIT_KHR | VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
            VK_PIPELINE_STAGE_TRANSFER_BIT,
            0, 0, nullptr, 1, &barrier, 0, nullptr);
        VkBufferCopy cp{};
        cp.srcOffset = 0; cp.dstOffset = 0; cp.size = 4;
        vkCmdCopyBuffer(cmd, m_trainingCount.handle, m_countReadback.handle, 1, &cp);

        // Query count
        barrier.buffer = m_queryCount.handle;
        vkCmdPipelineBarrier(cmd,
            VK_PIPELINE_STAGE_RAY_TRACING_SHADER_BIT_KHR | VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
            VK_PIPELINE_STAGE_TRANSFER_BIT,
            0, 0, nullptr, 1, &barrier, 0, nullptr);
        cp.dstOffset = 4;
        vkCmdCopyBuffer(cmd, m_queryCount.handle, m_countReadback.handle, 1, &cp);

        m_readbackRequested = false;
    }
}

void NrcPass::requestReadback() {
    m_readbackRequested = true;
}

NrcPass::FrameCounts NrcPass::readbackCounts() const {
    FrameCounts c;
    if (m_countReadbackMapped) {
        const uint32_t* p = reinterpret_cast<const uint32_t*>(m_countReadbackMapped);
        c.training = p[0];
        c.queries  = p[1];
    }
    return c;
}

void NrcPass::createDescriptorSet() {
    // 6 storage-buffer bindings at set=3.
    //   0 = TrainingRecord buffer
    //   1 = QueryRecord buffer
    //   2 = training count (uint)
    //   3 = query count    (uint)
    //   4 = NRC contribution buffer (float4 per pixel)
    //   5 = path-prefix buffer    (§1 same-frame; float4 per pixel)
    constexpr uint32_t kNumBindings = 6;
    VkDescriptorSetLayoutBinding bindings[kNumBindings] = {};
    for (uint32_t i = 0; i < kNumBindings; ++i) {
        bindings[i].binding         = i;
        bindings[i].descriptorType  = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
        bindings[i].descriptorCount = 1;
        bindings[i].stageFlags =
            VK_SHADER_STAGE_RAYGEN_BIT_KHR | VK_SHADER_STAGE_COMPUTE_BIT;
    }

    VkDescriptorSetLayoutCreateInfo lci{};
    lci.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO;
    lci.bindingCount = kNumBindings;
    lci.pBindings    = bindings;
    if (vkCreateDescriptorSetLayout(m_device, &lci, nullptr, &m_descSetLayout) != VK_SUCCESS)
        throw std::runtime_error("nrc: vkCreateDescriptorSetLayout failed");

    VkDescriptorPoolSize poolSize{};
    poolSize.type            = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
    poolSize.descriptorCount = kNumBindings;

    VkDescriptorPoolCreateInfo pci{};
    pci.sType         = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO;
    pci.maxSets       = 1;
    pci.poolSizeCount = 1;
    pci.pPoolSizes    = &poolSize;
    if (vkCreateDescriptorPool(m_device, &pci, nullptr, &m_descPool) != VK_SUCCESS)
        throw std::runtime_error("nrc: vkCreateDescriptorPool failed");

    VkDescriptorSetAllocateInfo ai{};
    ai.sType              = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO;
    ai.descriptorPool     = m_descPool;
    ai.descriptorSetCount = 1;
    ai.pSetLayouts        = &m_descSetLayout;
    if (vkAllocateDescriptorSets(m_device, &ai, &m_descSet) != VK_SUCCESS)
        throw std::runtime_error("nrc: vkAllocateDescriptorSets failed");

    VkDescriptorBufferInfo bi[kNumBindings] = {};
    bi[0].buffer = m_trainingRecords.handle;  bi[0].offset = 0; bi[0].range = VK_WHOLE_SIZE;
    bi[1].buffer = m_queryRecords.handle;     bi[1].offset = 0; bi[1].range = VK_WHOLE_SIZE;
    bi[2].buffer = m_trainingCount.handle;    bi[2].offset = 0; bi[2].range = VK_WHOLE_SIZE;
    bi[3].buffer = m_queryCount.handle;       bi[3].offset = 0; bi[3].range = VK_WHOLE_SIZE;
    bi[4].buffer = m_contribBuffer.handle;    bi[4].offset = 0; bi[4].range = VK_WHOLE_SIZE;
    bi[5].buffer = m_pathPrefixBuffer.handle; bi[5].offset = 0; bi[5].range = VK_WHOLE_SIZE;

    VkWriteDescriptorSet writes[kNumBindings] = {};
    for (uint32_t i = 0; i < kNumBindings; ++i) {
        writes[i].sType           = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
        writes[i].dstSet          = m_descSet;
        writes[i].dstBinding      = i;
        writes[i].descriptorCount = 1;
        writes[i].descriptorType  = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
        writes[i].pBufferInfo     = &bi[i];
    }
    vkUpdateDescriptorSets(m_device, kNumBindings, writes, 0, nullptr);
}

void NrcPass::destroyDescriptorSet() {
    if (m_descPool) {
        // Freeing the pool frees the sets allocated from it.
        vkDestroyDescriptorPool(m_device, m_descPool, nullptr);
        m_descPool = VK_NULL_HANDLE;
        m_descSet  = VK_NULL_HANDLE;
    }
    if (m_descSetLayout) {
        vkDestroyDescriptorSetLayout(m_device, m_descSetLayout, nullptr);
        m_descSetLayout = VK_NULL_HANDLE;
    }
}

VkBuffer NrcPass::inferenceWeightsBuffer() const {
    return m_useEmaWeights ? m_emaWeights.handle : m_primaryWeights.handle;
}

void NrcPass::updateInferenceWeightDescriptors() {
    if (!m_device) return;

    VkDescriptorBufferInfo bi{};
    bi.buffer = inferenceWeightsBuffer();
    bi.offset = 0;
    bi.range  = VK_WHOLE_SIZE;
    if (!bi.buffer) return;

    VkWriteDescriptorSet writes[2] = {};
    uint32_t writeCount = 0;
    if (m_cacheQueryDescSet) {
        writes[writeCount].sType           = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
        writes[writeCount].dstSet          = m_cacheQueryDescSet;
        writes[writeCount].dstBinding      = 2;
        writes[writeCount].descriptorCount = 1;
        writes[writeCount].descriptorType  = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
        writes[writeCount].pBufferInfo     = &bi;
        ++writeCount;
    }
    if (m_recordCompleteDescSet) {
        writes[writeCount].sType           = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
        writes[writeCount].dstSet          = m_recordCompleteDescSet;
        writes[writeCount].dstBinding      = 2;
        writes[writeCount].descriptorCount = 1;
        writes[writeCount].descriptorType  = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
        writes[writeCount].pBufferInfo     = &bi;
        ++writeCount;
    }
    if (writeCount)
        vkUpdateDescriptorSets(m_device, writeCount, writes, 0, nullptr);
}

// ---------------------------------------------------------------------------
// Cache-query compute pipeline.
// Descriptor set layout for the compute shader (set 0):
//   binding 0 : RWStructuredBuffer<QueryRecord> g_queries
//   binding 1 : RWStructuredBuffer<uint>        g_queryCount
//   binding 2 : ByteAddressBuffer               g_emaWeights
//   binding 3 : RWStructuredBuffer<float4>      g_nrcContrib
// Push constants: see the PushConstants struct below.
// ---------------------------------------------------------------------------

// Layout of push-constant data must match the Slang shader's `Pc` struct.
struct CacheQueryPushConstants {
    uint32_t matrixOffset[kNrcNumLayers];  // 6 uints = 24 B
    uint32_t biasOffset  [kNrcNumLayers];  // 6 uints = 24 B
    uint32_t maxQueries;
    uint32_t imageWidth;
    uint32_t imageHeight;
    uint32_t _pad;
};
static_assert(sizeof(CacheQueryPushConstants) == 64, "CacheQueryPushConstants must be 64 B");

void NrcPass::createCacheQueryPipeline() {
    // --- Descriptor set layout: 4 storage buffer bindings, compute stage. ---
    VkDescriptorSetLayoutBinding bindings[4] = {};
    for (uint32_t i = 0; i < 4; ++i) {
        bindings[i].binding         = i;
        bindings[i].descriptorType  = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
        bindings[i].descriptorCount = 1;
        bindings[i].stageFlags      = VK_SHADER_STAGE_COMPUTE_BIT;
    }
    VkDescriptorSetLayoutCreateInfo lci{};
    lci.sType        = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO;
    lci.bindingCount = 4;
    lci.pBindings    = bindings;
    if (vkCreateDescriptorSetLayout(m_device, &lci, nullptr, &m_cacheQueryDescLayout) != VK_SUCCESS)
        throw std::runtime_error("nrc: cacheQuery vkCreateDescriptorSetLayout failed");

    // --- Descriptor pool + set. ---
    VkDescriptorPoolSize poolSize{VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, 4};
    VkDescriptorPoolCreateInfo pci{};
    pci.sType         = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO;
    pci.maxSets       = 1;
    pci.poolSizeCount = 1;
    pci.pPoolSizes    = &poolSize;
    if (vkCreateDescriptorPool(m_device, &pci, nullptr, &m_cacheQueryDescPool) != VK_SUCCESS)
        throw std::runtime_error("nrc: cacheQuery vkCreateDescriptorPool failed");

    VkDescriptorSetAllocateInfo ai{};
    ai.sType              = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO;
    ai.descriptorPool     = m_cacheQueryDescPool;
    ai.descriptorSetCount = 1;
    ai.pSetLayouts        = &m_cacheQueryDescLayout;
    if (vkAllocateDescriptorSets(m_device, &ai, &m_cacheQueryDescSet) != VK_SUCCESS)
        throw std::runtime_error("nrc: cacheQuery vkAllocateDescriptorSets failed");

    VkDescriptorBufferInfo bi[4] = {};
    bi[0].buffer = m_queryRecords.handle;  bi[0].range = VK_WHOLE_SIZE;
    bi[1].buffer = m_queryCount.handle;    bi[1].range = VK_WHOLE_SIZE;
    bi[2].buffer = inferenceWeightsBuffer(); bi[2].range = VK_WHOLE_SIZE;
    bi[3].buffer = m_contribBuffer.handle; bi[3].range = VK_WHOLE_SIZE;
    VkWriteDescriptorSet writes[4] = {};
    for (uint32_t i = 0; i < 4; ++i) {
        writes[i].sType           = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
        writes[i].dstSet          = m_cacheQueryDescSet;
        writes[i].dstBinding      = i;
        writes[i].descriptorCount = 1;
        writes[i].descriptorType  = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
        writes[i].pBufferInfo     = &bi[i];
    }
    vkUpdateDescriptorSets(m_device, 4, writes, 0, nullptr);

    // --- Pipeline layout. ---
    VkPushConstantRange pcRange{};
    pcRange.stageFlags = VK_SHADER_STAGE_COMPUTE_BIT;
    pcRange.offset     = 0;
    pcRange.size       = sizeof(CacheQueryPushConstants);

    VkPipelineLayoutCreateInfo plci{};
    plci.sType                  = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
    plci.setLayoutCount         = 1;
    plci.pSetLayouts            = &m_cacheQueryDescLayout;
    plci.pushConstantRangeCount = 1;
    plci.pPushConstantRanges    = &pcRange;
    if (vkCreatePipelineLayout(m_device, &plci, nullptr, &m_cacheQueryLayout) != VK_SUCCESS)
        throw std::runtime_error("nrc: cacheQuery vkCreatePipelineLayout failed");

    // --- Shader module from embedded SPIR-V. ---
    VkShaderModuleCreateInfo smci{};
    smci.sType    = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
    smci.codeSize = sizeof(nrc_cache_query_comp_slang);
    smci.pCode    = nrc_cache_query_comp_slang;
    VkShaderModule sm = VK_NULL_HANDLE;
    if (vkCreateShaderModule(m_device, &smci, nullptr, &sm) != VK_SUCCESS)
        throw std::runtime_error("nrc: cacheQuery vkCreateShaderModule failed");

    VkComputePipelineCreateInfo cpci{};
    cpci.sType             = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO;
    cpci.stage.sType       = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    cpci.stage.stage       = VK_SHADER_STAGE_COMPUTE_BIT;
    cpci.stage.module      = sm;
    cpci.stage.pName       = "main";
    cpci.layout            = m_cacheQueryLayout;
    VkResult r = vkCreateComputePipelines(m_device, VK_NULL_HANDLE, 1, &cpci, nullptr, &m_cacheQueryPipeline);
    vkDestroyShaderModule(m_device, sm, nullptr);  // no longer needed after pipeline creation
    if (r != VK_SUCCESS)
        throw std::runtime_error("nrc: cacheQuery vkCreateComputePipelines failed");
}

void NrcPass::destroyCacheQueryPipeline() {
    if (m_cacheQueryPipeline) {
        vkDestroyPipeline(m_device, m_cacheQueryPipeline, nullptr);
        m_cacheQueryPipeline = VK_NULL_HANDLE;
    }
    if (m_cacheQueryLayout) {
        vkDestroyPipelineLayout(m_device, m_cacheQueryLayout, nullptr);
        m_cacheQueryLayout = VK_NULL_HANDLE;
    }
    if (m_cacheQueryDescPool) {
        vkDestroyDescriptorPool(m_device, m_cacheQueryDescPool, nullptr);
        m_cacheQueryDescPool = VK_NULL_HANDLE;
        m_cacheQueryDescSet  = VK_NULL_HANDLE;
    }
    if (m_cacheQueryDescLayout) {
        vkDestroyDescriptorSetLayout(m_device, m_cacheQueryDescLayout, nullptr);
        m_cacheQueryDescLayout = VK_NULL_HANDLE;
    }
}

// ---------------------------------------------------------------------------
// Small helpers shared by the three training-side pipelines below.
// ---------------------------------------------------------------------------

static VkDescriptorSetLayout makeComputeSetLayout(VkDevice dev, uint32_t nBindings) {
    std::vector<VkDescriptorSetLayoutBinding> bs(nBindings);
    for (uint32_t i = 0; i < nBindings; ++i) {
        bs[i].binding         = i;
        bs[i].descriptorType  = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
        bs[i].descriptorCount = 1;
        bs[i].stageFlags      = VK_SHADER_STAGE_COMPUTE_BIT;
    }
    VkDescriptorSetLayoutCreateInfo lci{};
    lci.sType        = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO;
    lci.bindingCount = nBindings;
    lci.pBindings    = bs.data();
    VkDescriptorSetLayout layout = VK_NULL_HANDLE;
    if (vkCreateDescriptorSetLayout(dev, &lci, nullptr, &layout) != VK_SUCCESS)
        throw std::runtime_error("nrc: vkCreateDescriptorSetLayout failed");
    return layout;
}

static void makeComputeSet(VkDevice dev, VkDescriptorSetLayout layout,
                           VkDescriptorPool& outPool, VkDescriptorSet& outSet,
                           uint32_t nBindings,
                           const VkBuffer* buffers)
{
    VkDescriptorPoolSize poolSize{VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, nBindings};
    VkDescriptorPoolCreateInfo pci{};
    pci.sType         = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO;
    pci.maxSets       = 1;
    pci.poolSizeCount = 1;
    pci.pPoolSizes    = &poolSize;
    if (vkCreateDescriptorPool(dev, &pci, nullptr, &outPool) != VK_SUCCESS)
        throw std::runtime_error("nrc: vkCreateDescriptorPool failed");

    VkDescriptorSetAllocateInfo ai{};
    ai.sType              = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO;
    ai.descriptorPool     = outPool;
    ai.descriptorSetCount = 1;
    ai.pSetLayouts        = &layout;
    if (vkAllocateDescriptorSets(dev, &ai, &outSet) != VK_SUCCESS)
        throw std::runtime_error("nrc: vkAllocateDescriptorSets failed");

    std::vector<VkDescriptorBufferInfo> bi(nBindings);
    std::vector<VkWriteDescriptorSet> writes(nBindings);
    for (uint32_t i = 0; i < nBindings; ++i) {
        bi[i].buffer = buffers[i];
        bi[i].offset = 0;
        bi[i].range  = VK_WHOLE_SIZE;
        writes[i].sType           = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
        writes[i].dstSet          = outSet;
        writes[i].dstBinding      = i;
        writes[i].descriptorCount = 1;
        writes[i].descriptorType  = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
        writes[i].pBufferInfo     = &bi[i];
    }
    vkUpdateDescriptorSets(dev, nBindings, writes.data(), 0, nullptr);
}

static VkPipelineLayout makeComputeLayout(VkDevice dev,
                                          VkDescriptorSetLayout dsl,
                                          uint32_t pushConstSize) {
    VkPushConstantRange pcRange{};
    pcRange.stageFlags = VK_SHADER_STAGE_COMPUTE_BIT;
    pcRange.offset     = 0;
    pcRange.size       = pushConstSize;

    VkPipelineLayoutCreateInfo plci{};
    plci.sType                  = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
    plci.setLayoutCount         = 1;
    plci.pSetLayouts            = &dsl;
    plci.pushConstantRangeCount = pushConstSize > 0 ? 1 : 0;
    plci.pPushConstantRanges    = pushConstSize > 0 ? &pcRange : nullptr;
    VkPipelineLayout layout = VK_NULL_HANDLE;
    if (vkCreatePipelineLayout(dev, &plci, nullptr, &layout) != VK_SUCCESS)
        throw std::runtime_error("nrc: vkCreatePipelineLayout failed");
    return layout;
}

static VkPipeline makeComputePipeline(VkDevice dev, VkPipelineLayout layout,
                                      const uint32_t* spv, size_t spvSize) {
    VkShaderModuleCreateInfo smci{};
    smci.sType    = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
    smci.codeSize = spvSize;
    smci.pCode    = spv;
    VkShaderModule sm = VK_NULL_HANDLE;
    if (vkCreateShaderModule(dev, &smci, nullptr, &sm) != VK_SUCCESS)
        throw std::runtime_error("nrc: vkCreateShaderModule failed");

    VkComputePipelineCreateInfo cpci{};
    cpci.sType        = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO;
    cpci.stage.sType  = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    cpci.stage.stage  = VK_SHADER_STAGE_COMPUTE_BIT;
    cpci.stage.module = sm;
    cpci.stage.pName  = "main";
    cpci.layout       = layout;
    VkPipeline p = VK_NULL_HANDLE;
    VkResult r = vkCreateComputePipelines(dev, VK_NULL_HANDLE, 1, &cpci, nullptr, &p);
    vkDestroyShaderModule(dev, sm, nullptr);
    if (r != VK_SUCCESS)
        throw std::runtime_error("nrc: vkCreateComputePipelines failed");
    return p;
}

void NrcPass::dispatchCacheQuery(VkCommandBuffer cmd) {
    if (!m_enabled || !m_cacheQueryPipeline) return;

    // Build push constants from the MLP layout we computed at init.
    CacheQueryPushConstants pc{};
    for (int i = 0; i < kNrcNumLayers; ++i) {
        pc.matrixOffset[i] = m_mlpLayout.weightOffset[i];
        pc.biasOffset[i]   = m_mlpLayout.biasOffset[i];
    }
    // §1 bugfix: ray-gen indexed g_nrcContrib by the actual gbuffer size
    // (setRenderSize), not by m_params. Use render size for imageWidth /
    // imageHeight so the cache-query shader writes at the right stride.
    // maxQueries / dispatch count stay at the params-size upper bound —
    // cache-query dispatches one thread per query record and early-returns on
    // threads beyond queryCount[0].
    pc.maxQueries  = m_params.frameWidth * m_params.frameHeight;
    pc.imageWidth  = (m_renderWidth  > 0) ? m_renderWidth  : m_params.frameWidth;
    pc.imageHeight = (m_renderHeight > 0) ? m_renderHeight : m_params.frameHeight;

    // Sync is handled by recordFramePost's barrier helpers (issueBarrierRayGenToCompute / issueBarrierToCompose).

    vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, m_cacheQueryPipeline);
    vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, m_cacheQueryLayout,
                            0, 1, &m_cacheQueryDescSet, 0, nullptr);
    vkCmdPushConstants(cmd, m_cacheQueryLayout, VK_SHADER_STAGE_COMPUTE_BIT,
                       0, sizeof(pc), &pc);

    // Dispatch one thread per potential query. Each workgroup is 128 threads.
    // In practice only queryCount[0] threads actually do work; the rest early-return.
    // For shader-ball at 1080p that's ~161k queries → ~1300 workgroups. Conservative
    // upper bound: dispatch enough to cover the whole frame.
    uint32_t totalThreads = m_params.frameWidth * m_params.frameHeight;
    uint32_t groups       = (totalThreads + 127u) / 128u;
    vkCmdDispatch(cmd, groups, 1, 1);

    // Sync is handled by recordFramePost's barrier helpers (issueBarrierRayGenToCompute / issueBarrierToCompose).
}

// ===========================================================================
// Record-completion pipeline (Task 11b)
// ===========================================================================
struct RecordCompletePushConstants {
    uint32_t matrixOffset[kNrcNumLayers];
    uint32_t biasOffset  [kNrcNumLayers];
    uint32_t maxRecords;
    uint32_t pad0, pad1, pad2;
};
static_assert(sizeof(RecordCompletePushConstants) == 64, "RecordCompletePushConstants size mismatch");

void NrcPass::createRecordCompletePipeline() {
    m_recordCompleteDescLayout = makeComputeSetLayout(m_device, 4);
    VkBuffer buffers[4] = {
        m_trainingRecords.handle,
        m_trainingCount.handle,
        inferenceWeightsBuffer(),
        m_trainingTargets.handle,
    };
    makeComputeSet(m_device, m_recordCompleteDescLayout,
                   m_recordCompleteDescPool, m_recordCompleteDescSet,
                   4, buffers);
    m_recordCompleteLayout = makeComputeLayout(m_device, m_recordCompleteDescLayout,
                                               sizeof(RecordCompletePushConstants));
    m_recordCompletePipeline = makeComputePipeline(m_device, m_recordCompleteLayout,
                                                   nrc_record_complete_comp_slang,
                                                   sizeof(nrc_record_complete_comp_slang));
}

void NrcPass::destroyRecordCompletePipeline() {
    if (m_recordCompletePipeline)   { vkDestroyPipeline(m_device, m_recordCompletePipeline, nullptr); m_recordCompletePipeline = VK_NULL_HANDLE; }
    if (m_recordCompleteLayout)     { vkDestroyPipelineLayout(m_device, m_recordCompleteLayout, nullptr); m_recordCompleteLayout = VK_NULL_HANDLE; }
    if (m_recordCompleteDescPool)   { vkDestroyDescriptorPool(m_device, m_recordCompleteDescPool, nullptr); m_recordCompleteDescPool = VK_NULL_HANDLE; m_recordCompleteDescSet = VK_NULL_HANDLE; }
    if (m_recordCompleteDescLayout) { vkDestroyDescriptorSetLayout(m_device, m_recordCompleteDescLayout, nullptr); m_recordCompleteDescLayout = VK_NULL_HANDLE; }
}

void NrcPass::dispatchRecordCompletion(VkCommandBuffer cmd) {
    if (!m_enabled || !m_recordCompletePipeline) return;

    RecordCompletePushConstants pc{};
    for (int i = 0; i < kNrcNumLayers; ++i) {
        pc.matrixOffset[i] = m_mlpLayout.weightOffset[i];
        pc.biasOffset[i]   = m_mlpLayout.biasOffset[i];
    }
    pc.maxRecords = m_params.trainingRecordsPerFrame;

    // Barrier: trainingRecords + trainingCount just written by ray-gen
    VkBufferMemoryBarrier barriers[2] = {};
    for (int i = 0; i < 2; ++i) {
        barriers[i].sType = VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER;
        barriers[i].srcAccessMask = VK_ACCESS_SHADER_WRITE_BIT;
        barriers[i].dstAccessMask = VK_ACCESS_SHADER_READ_BIT;
        barriers[i].srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
        barriers[i].dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
        barriers[i].size = VK_WHOLE_SIZE;
    }
    barriers[0].buffer = m_trainingRecords.handle;
    barriers[1].buffer = m_trainingCount.handle;
    vkCmdPipelineBarrier(cmd,
        VK_PIPELINE_STAGE_RAY_TRACING_SHADER_BIT_KHR | VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
        VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
        0, 0, nullptr, 2, barriers, 0, nullptr);

    vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, m_recordCompletePipeline);
    vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, m_recordCompleteLayout,
                            0, 1, &m_recordCompleteDescSet, 0, nullptr);
    vkCmdPushConstants(cmd, m_recordCompleteLayout, VK_SHADER_STAGE_COMPUTE_BIT,
                       0, sizeof(pc), &pc);
    uint32_t groups = (m_params.trainingRecordsPerFrame + 127u) / 128u;
    vkCmdDispatch(cmd, groups, 1, 1);

    // Barrier: trainingTargets now written, trainPass reads it next.
    VkBufferMemoryBarrier b{};
    b.sType = VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER;
    b.srcAccessMask = VK_ACCESS_SHADER_WRITE_BIT;
    b.dstAccessMask = VK_ACCESS_SHADER_READ_BIT;
    b.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
    b.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
    b.buffer = m_trainingTargets.handle;
    b.size = VK_WHOLE_SIZE;
    vkCmdPipelineBarrier(cmd,
        VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT, VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
        0, 0, nullptr, 1, &b, 0, nullptr);
}

// ===========================================================================
// Training pipeline (Task 11c)
// §3 (Task 3): stepIdx + recordCount added. Adam loop runs 4 steps/frame,
// each dispatching recordsPerBatch threads that read shuffled indices from
// a disjoint LCG slice of the full record pool.
// ===========================================================================
struct TrainPushConstants {
    uint32_t matrixOffset[kNrcNumLayers];
    uint32_t biasOffset  [kNrcNumLayers];
    uint32_t maxRecords;
    float    lossScale;
    uint32_t stepIdx;      // 0..adamStepsPerFrame-1  (§3)
    uint32_t recordCount;  // live count from previous frame readback (§3)
};
static_assert(sizeof(TrainPushConstants) == 64, "TrainPushConstants size mismatch");

void NrcPass::createTrainPipeline() {
    m_trainDescLayout = makeComputeSetLayout(m_device, 5);
    VkBuffer buffers[5] = {
        m_trainingRecords.handle,
        m_trainingCount.handle,
        m_trainingTargets.handle,
        m_primaryWeights.handle,
        m_gradients.handle,
    };
    makeComputeSet(m_device, m_trainDescLayout,
                   m_trainDescPool, m_trainDescSet, 5, buffers);
    m_trainLayout = makeComputeLayout(m_device, m_trainDescLayout,
                                      sizeof(TrainPushConstants));
    m_trainPipeline = makeComputePipeline(m_device, m_trainLayout,
                                          nrc_train_comp_slang,
                                          sizeof(nrc_train_comp_slang));
}

void NrcPass::destroyTrainPipeline() {
    if (m_trainPipeline)     { vkDestroyPipeline(m_device, m_trainPipeline, nullptr); m_trainPipeline = VK_NULL_HANDLE; }
    if (m_trainLayout)       { vkDestroyPipelineLayout(m_device, m_trainLayout, nullptr); m_trainLayout = VK_NULL_HANDLE; }
    if (m_trainDescPool)     { vkDestroyDescriptorPool(m_device, m_trainDescPool, nullptr); m_trainDescPool = VK_NULL_HANDLE; m_trainDescSet = VK_NULL_HANDLE; }
    if (m_trainDescLayout)   { vkDestroyDescriptorSetLayout(m_device, m_trainDescLayout, nullptr); m_trainDescLayout = VK_NULL_HANDLE; }
}

void NrcPass::dispatchTrain(VkCommandBuffer cmd) {
    if (!m_enabled || !m_trainPipeline) return;

    TrainPushConstants pc{};
    for (int i = 0; i < kNrcNumLayers; ++i) {
        pc.matrixOffset[i] = m_mlpLayout.weightOffset[i];
        pc.biasOffset[i]   = m_mlpLayout.biasOffset[i];
    }
    pc.maxRecords = m_params.trainingRecordsPerFrame;
    pc.lossScale  = 128.0f;   // Standard NRC loss-scale for fp16 stability.
    // §3 (Task 3): stepIdx and recordCount are set by the caller in
    // recordFramePost's Adam loop — dispatchTrain uses the values from the
    // m_trainStepIdx / m_lastKnownRecordCount members written just before.
    pc.stepIdx     = m_trainStepIdx;
    pc.recordCount = m_lastKnownRecordCount > 0
                     ? m_lastKnownRecordCount
                     : m_params.trainingRecordsPerFrame;  // fallback for frame 0

    vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, m_trainPipeline);
    vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, m_trainLayout,
                            0, 1, &m_trainDescSet, 0, nullptr);
    vkCmdPushConstants(cmd, m_trainLayout, VK_SHADER_STAGE_COMPUTE_BIT,
                       0, sizeof(pc), &pc);
    // §3: dispatch one thread per record in the batch (recordsPerBatch = 16384);
    // the shader handles its own stepIdx offset via LCG shuffle.
    uint32_t groups = (m_params.recordsPerBatch + 127u) / 128u;
    vkCmdDispatch(cmd, groups, 1, 1);

    // Barrier: gradients are now being written.
    VkBufferMemoryBarrier b{};
    b.sType = VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER;
    b.srcAccessMask = VK_ACCESS_SHADER_WRITE_BIT;
    b.dstAccessMask = VK_ACCESS_SHADER_READ_BIT | VK_ACCESS_SHADER_WRITE_BIT;
    b.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
    b.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
    b.buffer = m_gradients.handle;
    b.size = VK_WHOLE_SIZE;
    vkCmdPipelineBarrier(cmd,
        VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT, VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
        0, 0, nullptr, 1, &b, 0, nullptr);
}

// ===========================================================================
// Optimizer pipeline (Task 11d) — Adam + EMA update
// ===========================================================================
struct OptimizerPushConstants {
    uint32_t elementCount;
    uint32_t adamStep;
    float    learningRate;
    float    beta1;
    float    beta2;
    float    eps;
    float    emaAlpha;
    float    gradientScale;
};
static_assert(sizeof(OptimizerPushConstants) == 32, "OptimizerPushConstants size mismatch");

void NrcPass::createOptimizerPipeline() {
    m_optimizerDescLayout = makeComputeSetLayout(m_device, 4);
    VkBuffer buffers[4] = {
        m_primaryWeights.handle,
        m_emaWeights.handle,
        m_gradients.handle,
        m_adamMoments.handle,
    };
    makeComputeSet(m_device, m_optimizerDescLayout,
                   m_optimizerDescPool, m_optimizerDescSet, 4, buffers);
    m_optimizerLayout = makeComputeLayout(m_device, m_optimizerDescLayout,
                                          sizeof(OptimizerPushConstants));
    m_optimizerPipeline = makeComputePipeline(m_device, m_optimizerLayout,
                                              nrc_optimizer_comp_slang,
                                              sizeof(nrc_optimizer_comp_slang));
}

void NrcPass::destroyOptimizerPipeline() {
    if (m_optimizerPipeline)     { vkDestroyPipeline(m_device, m_optimizerPipeline, nullptr); m_optimizerPipeline = VK_NULL_HANDLE; }
    if (m_optimizerLayout)       { vkDestroyPipelineLayout(m_device, m_optimizerLayout, nullptr); m_optimizerLayout = VK_NULL_HANDLE; }
    if (m_optimizerDescPool)     { vkDestroyDescriptorPool(m_device, m_optimizerDescPool, nullptr); m_optimizerDescPool = VK_NULL_HANDLE; m_optimizerDescSet = VK_NULL_HANDLE; }
    if (m_optimizerDescLayout)   { vkDestroyDescriptorSetLayout(m_device, m_optimizerDescLayout, nullptr); m_optimizerDescLayout = VK_NULL_HANDLE; }
}

void NrcPass::dispatchOptimizer(VkCommandBuffer cmd) {
    if (!m_enabled || !m_optimizerPipeline) return;

    m_adamStep++;

    OptimizerPushConstants pc{};
    pc.elementCount  = m_mlpLayout.totalBytes / kNrcElementBytes;
    pc.adamStep      = m_adamStep;
    pc.learningRate  = 0.002f;  // Adam step size.
    pc.beta1         = 0.9f;
    pc.beta2         = 0.999f;
    pc.eps           = 1e-8f;
    pc.emaAlpha      = m_params.emaAlpha;
    pc.gradientScale = 1.0f / (128.0f * float(m_params.recordsPerBatch));  // inverse lossScale and batch mean

    vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, m_optimizerPipeline);
    vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, m_optimizerLayout,
                            0, 1, &m_optimizerDescSet, 0, nullptr);
    vkCmdPushConstants(cmd, m_optimizerLayout, VK_SHADER_STAGE_COMPUTE_BIT,
                       0, sizeof(pc), &pc);
    uint32_t groups = (pc.elementCount + 63u) / 64u;
    vkCmdDispatch(cmd, groups, 1, 1);

    // Barrier: new primary/ema weights are now visible to subsequent compute
    // or ray-tracing reads (next Adam step, cache-query on next frame).
    VkBufferMemoryBarrier b[2] = {};
    for (int i = 0; i < 2; ++i) {
        b[i].sType = VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER;
        b[i].srcAccessMask = VK_ACCESS_SHADER_WRITE_BIT;
        b[i].dstAccessMask = VK_ACCESS_SHADER_READ_BIT;
        b[i].srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
        b[i].dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
        b[i].size = VK_WHOLE_SIZE;
    }
    b[0].buffer = m_primaryWeights.handle;
    b[1].buffer = m_emaWeights.handle;
    vkCmdPipelineBarrier(cmd,
        VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
        VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT | VK_PIPELINE_STAGE_RAY_TRACING_SHADER_BIT_KHR,
        0, 0, nullptr, 2, b, 0, nullptr);
}

// ===========================================================================
// §1 Compose pipeline — sums g_pathPrefix + g_nrcContrib into the output
// image, with frame-accumulation blending so NRC-on and NRC-off share the
// same per-frame sample-averaging semantics.
// ===========================================================================
struct ComposePushConstants {
    uint32_t imageWidth;
    uint32_t imageHeight;
    uint32_t numSamples;
    uint32_t totalSamples;
    uint32_t firstFrameOrReset;
    uint32_t _pad0;
    uint32_t _pad1;
    uint32_t _pad2;
};
static_assert(sizeof(ComposePushConstants) == 32, "ComposePushConstants size mismatch");

void NrcPass::createComposePipeline() {
    // Descriptor set layout: 2 storage-buffer bindings + 1 storage image.
    VkDescriptorSetLayoutBinding bindings[3] = {};
    bindings[0].binding         = 0;
    bindings[0].descriptorType  = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
    bindings[0].descriptorCount = 1;
    bindings[0].stageFlags      = VK_SHADER_STAGE_COMPUTE_BIT;
    bindings[1].binding         = 1;
    bindings[1].descriptorType  = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
    bindings[1].descriptorCount = 1;
    bindings[1].stageFlags      = VK_SHADER_STAGE_COMPUTE_BIT;
    bindings[2].binding         = 2;
    bindings[2].descriptorType  = VK_DESCRIPTOR_TYPE_STORAGE_IMAGE;
    bindings[2].descriptorCount = 1;
    bindings[2].stageFlags      = VK_SHADER_STAGE_COMPUTE_BIT;

    VkDescriptorSetLayoutCreateInfo lci{};
    lci.sType        = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO;
    lci.bindingCount = 3;
    lci.pBindings    = bindings;
    if (vkCreateDescriptorSetLayout(m_device, &lci, nullptr, &m_composeDescLayout) != VK_SUCCESS)
        throw std::runtime_error("nrc: compose vkCreateDescriptorSetLayout failed");

    // Descriptor pool + set.
    VkDescriptorPoolSize poolSizes[2]{};
    poolSizes[0].type            = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
    poolSizes[0].descriptorCount = 2;
    poolSizes[1].type            = VK_DESCRIPTOR_TYPE_STORAGE_IMAGE;
    poolSizes[1].descriptorCount = 1;
    VkDescriptorPoolCreateInfo pci{};
    pci.sType         = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO;
    pci.maxSets       = 1;
    pci.poolSizeCount = 2;
    pci.pPoolSizes    = poolSizes;
    if (vkCreateDescriptorPool(m_device, &pci, nullptr, &m_composeDescPool) != VK_SUCCESS)
        throw std::runtime_error("nrc: compose vkCreateDescriptorPool failed");

    VkDescriptorSetAllocateInfo ai{};
    ai.sType              = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO;
    ai.descriptorPool     = m_composeDescPool;
    ai.descriptorSetCount = 1;
    ai.pSetLayouts        = &m_composeDescLayout;
    if (vkAllocateDescriptorSets(m_device, &ai, &m_composeDescSet) != VK_SUCCESS)
        throw std::runtime_error("nrc: compose vkAllocateDescriptorSets failed");

    // Static writes for the two buffers; the storage image (binding 2) is
    // updated per-frame from the host because the view isn't known yet.
    VkDescriptorBufferInfo bi[2] = {};
    bi[0].buffer = m_pathPrefixBuffer.handle; bi[0].range = VK_WHOLE_SIZE;
    bi[1].buffer = m_contribBuffer.handle;    bi[1].range = VK_WHOLE_SIZE;
    VkWriteDescriptorSet bufWrites[2] = {};
    for (uint32_t i = 0; i < 2; ++i) {
        bufWrites[i].sType           = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
        bufWrites[i].dstSet          = m_composeDescSet;
        bufWrites[i].dstBinding      = i;
        bufWrites[i].descriptorCount = 1;
        bufWrites[i].descriptorType  = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
        bufWrites[i].pBufferInfo     = &bi[i];
    }
    vkUpdateDescriptorSets(m_device, 2, bufWrites, 0, nullptr);

    // Pipeline layout.
    VkPushConstantRange pcRange{};
    pcRange.stageFlags = VK_SHADER_STAGE_COMPUTE_BIT;
    pcRange.offset     = 0;
    pcRange.size       = sizeof(ComposePushConstants);
    VkPipelineLayoutCreateInfo plci{};
    plci.sType                  = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
    plci.setLayoutCount         = 1;
    plci.pSetLayouts            = &m_composeDescLayout;
    plci.pushConstantRangeCount = 1;
    plci.pPushConstantRanges    = &pcRange;
    if (vkCreatePipelineLayout(m_device, &plci, nullptr, &m_composeLayout) != VK_SUCCESS)
        throw std::runtime_error("nrc: compose vkCreatePipelineLayout failed");

    // Shader module.
    m_composePipeline = makeComputePipeline(m_device, m_composeLayout,
                                            nrc_compose_comp_slang,
                                            sizeof(nrc_compose_comp_slang));
}

void NrcPass::destroyComposePipeline() {
    if (m_composePipeline)     { vkDestroyPipeline(m_device, m_composePipeline, nullptr); m_composePipeline = VK_NULL_HANDLE; }
    if (m_composeLayout)       { vkDestroyPipelineLayout(m_device, m_composeLayout, nullptr); m_composeLayout = VK_NULL_HANDLE; }
    if (m_composeDescPool)     { vkDestroyDescriptorPool(m_device, m_composeDescPool, nullptr); m_composeDescPool = VK_NULL_HANDLE; m_composeDescSet = VK_NULL_HANDLE; }
    if (m_composeDescLayout)   { vkDestroyDescriptorSetLayout(m_device, m_composeDescLayout, nullptr); m_composeDescLayout = VK_NULL_HANDLE; }
    m_boundComposeImageView = VK_NULL_HANDLE;
}

void NrcPass::dispatchCompose(VkCommandBuffer cmd) {
    if (!m_enabled || !m_composePipeline) return;
    if (m_outImageView == VK_NULL_HANDLE) return;  // host didn't plumb it

    // Update binding 2 (storage image) whenever the view changes (e.g. on
    // window-resize the gbuffer is recreated and gets a new VkImageView).
    if (m_outImageView != m_boundComposeImageView) {
        VkDescriptorImageInfo imgInfo{};
        imgInfo.imageView   = m_outImageView;
        imgInfo.imageLayout = VK_IMAGE_LAYOUT_GENERAL;
        VkWriteDescriptorSet w{};
        w.sType           = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
        w.dstSet          = m_composeDescSet;
        w.dstBinding      = 2;
        w.descriptorCount = 1;
        w.descriptorType  = VK_DESCRIPTOR_TYPE_STORAGE_IMAGE;
        w.pImageInfo      = &imgInfo;
        vkUpdateDescriptorSets(m_device, 1, &w, 0, nullptr);
        m_boundComposeImageView = m_outImageView;
    }

    // §1 bugfix: ray-gen wrote g_pathPrefix with stride = gbuffer size
    // (setRenderSize), not m_params. Use the render size here so compose
    // indexes the right pixels — otherwise scanline garbage.
    ComposePushConstants pc{};
    pc.imageWidth        = (m_renderWidth  > 0) ? m_renderWidth  : m_params.frameWidth;
    pc.imageHeight       = (m_renderHeight > 0) ? m_renderHeight : m_params.frameHeight;
    pc.numSamples        = m_accumNumSamples;
    pc.totalSamples      = m_accumTotalSamples;
    pc.firstFrameOrReset = m_accumFirstFrameOrReset ? 1u : 0u;

    vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, m_composePipeline);
    vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, m_composeLayout,
                            0, 1, &m_composeDescSet, 0, nullptr);
    vkCmdPushConstants(cmd, m_composeLayout, VK_SHADER_STAGE_COMPUTE_BIT,
                       0, sizeof(pc), &pc);

    // Group count sized to actual render extent, not the init upper bound,
    // so we don't waste groups writing off-image pixels.
    uint32_t gx = (pc.imageWidth  + 15u) / 16u;
    uint32_t gy = (pc.imageHeight + 15u) / 16u;
    vkCmdDispatch(cmd, gx, gy, 1);
}

// §1 helpers — thin pipeline-barrier wrappers used by recordFramePost.

void NrcPass::issueBarrierRayGenToCompute(VkCommandBuffer cmd) {
    // Ray-gen just wrote: g_trainingRecords, g_queryRecords, counters,
    // g_pathPrefix, and the per-pixel clear of g_nrcContrib. Compute passes
    // need those writes visible before they read or overwrite the buffers.
    VkBufferMemoryBarrier bs[6] = {};
    for (int i = 0; i < 6; ++i) {
        bs[i].sType               = VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER;
        bs[i].srcAccessMask       = VK_ACCESS_SHADER_WRITE_BIT;
        bs[i].dstAccessMask       = VK_ACCESS_SHADER_READ_BIT | VK_ACCESS_SHADER_WRITE_BIT;
        bs[i].srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
        bs[i].dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
        bs[i].size                = VK_WHOLE_SIZE;
    }
    bs[0].buffer = m_trainingRecords.handle;
    bs[1].buffer = m_queryRecords.handle;
    bs[2].buffer = m_trainingCount.handle;
    bs[3].buffer = m_queryCount.handle;
    bs[4].buffer = m_pathPrefixBuffer.handle;
    bs[5].buffer = m_contribBuffer.handle;
    vkCmdPipelineBarrier(cmd,
        VK_PIPELINE_STAGE_RAY_TRACING_SHADER_BIT_KHR | VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
        VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
        0, 0, nullptr, 6, bs, 0, nullptr);
}

void NrcPass::issueBarrierOptimizerToCacheQuery(VkCommandBuffer cmd) {
    // Optimizer wrote primary and EMA weights. Cache-query and record-complete
    // can read either one depending on the UI's Use EMA toggle.
    VkBufferMemoryBarrier b[2] = {};
    for (int i = 0; i < 2; ++i) {
        b[i].sType               = VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER;
        b[i].srcAccessMask       = VK_ACCESS_SHADER_WRITE_BIT;
        b[i].dstAccessMask       = VK_ACCESS_SHADER_READ_BIT;
        b[i].srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
        b[i].dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
        b[i].size                = VK_WHOLE_SIZE;
    }
    b[0].buffer = m_primaryWeights.handle;
    b[1].buffer = m_emaWeights.handle;
    vkCmdPipelineBarrier(cmd,
        VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT, VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
        0, 0, nullptr, 2, b, 0, nullptr);
}

void NrcPass::issueBarrierToCompose(VkCommandBuffer cmd) {
    // Cache-query wrote g_nrcContrib; compose reads it. Ray-gen already
    // wrote g_pathPrefix (released by issueBarrierRayGenToCompute above, but
    // cache-query may re-execute on contrib between — we re-issue here for
    // clarity and to handle the case where compose runs without cache-query
    // (not currently, but plausible future toggle).
    VkBufferMemoryBarrier bs[2] = {};
    for (int i = 0; i < 2; ++i) {
        bs[i].sType               = VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER;
        bs[i].srcAccessMask       = VK_ACCESS_SHADER_WRITE_BIT;
        bs[i].dstAccessMask       = VK_ACCESS_SHADER_READ_BIT;
        bs[i].srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
        bs[i].dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
        bs[i].size                = VK_WHOLE_SIZE;
    }
    bs[0].buffer = m_contribBuffer.handle;
    bs[1].buffer = m_pathPrefixBuffer.handle;
    vkCmdPipelineBarrier(cmd,
        VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT | VK_PIPELINE_STAGE_RAY_TRACING_SHADER_BIT_KHR,
        VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
        0, 0, nullptr, 2, bs, 0, nullptr);
}

}  // namespace nrc
